# Generated by Django 5.2.16 on 2026-07-13 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(db_index=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='profissionais.profissional')),
            ],
            options={
                'ordering': ['-data_hora'],
                'constraints': [models.UniqueConstraint(fields=('profissional', 'data_hora'), name='uniq_profissional_data_hora')],
            },
        ),
    ]
